$HOME/.config/hypr/themes/theme.conf|> $HOME/.config/hypr/themes/colors.conf

$GTK_THEME = Oxo-Carbon
$ICON_THEME = Tela-circle-pink
$COLOR_SCHEME=prefer-dark
$CURSOR_THEME = Capitaine-Cursors
$CURSOR_SIZE=20
$CODE_THEME=oxocarbon

exec = gsettings set org.gnome.desktop.interface icon-theme '$ICON_THEME'
exec = gsettings set org.gnome.desktop.interface gtk-theme '$GTK_THEME'
exec = gsettings set org.gnome.desktop.interface color-scheme '$COLOR_SCHEME'
exec = Hyde cursor theme '$CURSOR_THEME' size $CURSOR_SIZE
exec = Hyde code theme '$CODE_THEME'

general {
    gaps_in = 3
    gaps_out = 8
    border_size = 2
    col.active_border = rgba(eb6f92ff) rgba(c4a7e7ff) 45deg
    col.inactive_border = rgba(31748fcc) rgba(9ccfd8cc) 45deg
    layout = dwindle
    resize_on_border = true
}

group {
    col.border_active = rgba(eb6f92ff) rgba(c4a7e7ff) 45deg
    col.border_inactive = rgba(31748fcc) rgba(9ccfd8cc) 45deg
    col.border_locked_active = rgba(eb6f92ff) rgba(c4a7e7ff) 45deg
    col.border_locked_inactive = rgba(31748fcc) rgba(9ccfd8cc) 45deg
}

decoration {
    rounding = 10

    blur {
        enabled = yes
        size = 6
        passes = 3
        new_optimizations = on
        ignore_opacity = on
        xray = false
    }

    shadow {
        enabled = false
    }
}

layerrule = blur,waybar
